---
# task file for installing and configuring cobbler on CentOS

- name: "disable selinux "
  lineinfile: dest=/etc/selinux/config regexp="^SELINUX=" line="SELINUX=disabled"

- name: "stop selinux"
  selinux: state=disabled

- name: stop and disable firewalld
  service: name=firewalld state=stopped enabled=no

- name: install epel repo
  yum: name=epel-release state=present

- name: install related packages
  yum: name={{ item }} state=present
  with_items:
    - cobbler  # cobbler depends on PyYAML, createrepo, httpd, mod_wsgi, rsync, tftp-server and so on.
    - dhcp
    - pykickstart


- name: generate crypted password
  shell: openssl passwd -1 {{ cobbler_default_password }}
  register: cobbler_default_password_crypted

- name: template /etc/cobbler/settings
  template: src=etc/cobbler/settings.j2 dest=/etc/cobbler/settings backup=yes
  notify: restart cobblerd

- name: template /etc/cobbler/dhcp.template
  template: src=etc/cobbler/dhcp.template.j2 dest=/etc/cobbler/dhcp.template backup=yes

- name: change 'disable' to 'no' in /etc/xinetd.d/tftp
  lineinfile: dest=/etc/xinetd.d/tftp regexp="disable" line="disable = no" backup=yes

#----------------
# begin add snippets and kickstarts
#----------------
- name: add_public_key_for_root snippnet
  template: src=var/lib/cobbler/snippets/add_public_key_for_root.j2
            dest=/var/lib/cobbler/snippets/add_public_key_for_root
            backup=yes
  when: cobbler_root_public_keys is defined

- name: post_install_network_config_ignore_interface snippnet
  template: src=var/lib/cobbler/snippets/post_install_network_config_ignore_interface.j2
            dest=/var/lib/cobbler/snippets/post_install_network_config_ignore_interface
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-customized-sda
  template: src=var/lib/cobbler/kickstarts/centos7-customized-sda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-customized-sda
            backup=yes

- name: /var/lib/cobbler/kickstarts/centos7-customized-vda
  template: src=var/lib/cobbler/kickstarts/centos7-customized-vda.j2
            dest=/var/lib/cobbler/kickstarts/centos7-customized-vda
            backup=yes


# end add snippets and kickstarts

- name: start and enable service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rsyncd
    - tftp
    - httpd
    - cobblerd

- name: cobbler get-loaders
  shell: cobbler get-loaders

#---------------
# import distros
#---------------
- name: mount device or iso to mount point
  mount: name=/mnt/{{ item.distro_name }}
         src={{ item.device_or_iso_path }}
         opts=ro fstype=iso9660 state=mounted
  with_items: "{{ cobbler_distros | default([])}}"
  when: cobbler_distros is defined

- name: import to distro to cobbler
  shell: cobbler import --name={{ item.distro_name }}
         --arch={{ item.arch }}
         --path=/mnt/{{ item.distro_name }}
         --kickstart=/var/lib/cobbler/kickstarts/{{ item.kickstart_file_name }}
  when: cobbler_distros is defined
  with_items: "{{ cobbler_distros | default([])}}"
  ignore_errors: true

- name: cobbler sync
  shell: cobbler sync


# cobbler-web
- name: install cobbler-web
  include: web.yml
  when: cobbler_install_web is defined and cobbler_install_web




