---
- name: ホスト上のユーザ一覧を取得
  hosts: all
  tasks:
    - name: /etc/passwdからユーザ名を抜き出す
      command: cut --delimiter=":" --fields=1 /etc/passwd
      register: usernames_result

    - name: usernames_result 変数をdebug表示
      debug:
        var: usernames_result
    - name: コマンド実行結果から存在するユーザ名のリストを作成
      set_fact:
        username_list: "{{ usernames_result.stdout_lines }}"
    - name: vagrantユーザが存在する場合にメッセージを表示
      debug:
        msg: このマシンにはvagrantユーザが存在します
      when: "'Vagrant' in username_list"
    - name: すべてのユーザが実在するか確認
      user:
        name: "{{ item }}"
        createhome: false
      with_items: "{{ username_list }}"
    - name: 複数のリストをまとめてループ
      become: true
      vars:
        development_packages:
          - gcc
          - make
        openssl_packages:
          - openssl
          - openssl-devel
      yum:
        name: "{{ item }}"
      with_items:
        - "{{ development_packages }}"
        - "{{ openssl_packages }}"

