---
- name: ホスト上のユーザ一覧を取得
  hosts: all
  tasks:
    - name: /etc/passwdからユーザ名を抜き出す
      command: cut --delimiter=":" --fields=1 /etc/passwd
      register: usernames_result

    - name: usernames_result 変数をdebug表示
      debug:
        var: usernames_result
    - name: コマンド実行結果から存在するユーザ名のリストを作成
      set_fact:
        username_list: "{{ usernames_result.stdout_lines }}"
    - name: vagrantユーザが存在する場合にメッセージを表示
      debug:
        msg: このマシンにはvagrantユーザが存在します
      when: "'Vagrant' in username_list"
    - name: すべてのユーザが実在するか確認
      user:
        name: "{{ item }}"
        createhome: false
      with_items: "{{ username_list }}"
    - name: 複数のリストをまとめてループ
      become: true
      vars:
        development_packages:
          - gcc
          - make
        openssl_packages:
          - openssl
          - openssl-devel
      yum:
        name: "{{ package_name }}"
      with_items:
        - "{{ development_packages }}"
        - "{{ openssl_packages }}"
      loop_control:
        loop_var: package_name
    - name: マジック変数(hostvars)の動作確認
      debug:
        msg: "{{ hostvars['vagrant-machine'].ansible_distribution }}"
      run_once: true
    - name: マジック変数(groups)の動作確認
      debug:
        var: groups
    - name: マジック変数(group_names)の動作確認
      debug:
        var: group_names


