---
- name: create instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    machine_type: f1-micro
    image: centos-7-v20170426
    zone: asia-northeast1-a
    state: present
  tasks:
    - name: launch instances
      gce:
        instance_names: sample-secretspy
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        state: "{{ state }}"

