---
- name: create instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - kal3v.gce-init

  vars:
    machine_type: f1-micro
    project_id: decoded-vision-166013
    instance_name: sample
