---
- name: create instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    machine_type: f1-micro

  tasks:
    - name: launch instance
      gem:
        instance_name: sample
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
