---
- name: Playbookチュートリアル
  hosts: all
  become: true
  roles:
    - role: nginx
  tasks:
    - name: /tmp/dir1を作成
      file:
        path: /tmp/dir1
        state: directory
    - name: Link作成サンプルPlay
      file:
        src: /tmp/dir1
        dest: /tmp/link_to_dir1
        state: link
    - name: 権限変更サンプルPlay
      file:
        path: /tmp/dir1
        state: directory
        owner: vagrant 
        group: vagrant 
        mode: 0700
    - name: ファイルコピーサンプルPlay
      copy:
        src: ~/Downloads/IMG_0014.JPG
        dest: /tmp
    - name: 既存ファイルを行単位で修正
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin\s+'
        #line: PermitRootLogin without-password
        state: absent
        validate: sshd -t -f %s
      notify:
        - sshd再起動
    - name: tmpディレクトリにパスフレーズなしのSSH鍵を生成
      command: "/usr/bin/ssh-keygen -b 2048 -t rsa -N '' -f /tmp/new-id_rsa"
      args:
        creates: /tmp/new-id_rsa
    - name: 環境変数出力Play
      command: "echo {{ ansible_env.HOME | quote }}"
      register: echo_output
    - name: echoの結果を標準出力に出力する
      debug:
        msg: "{{ echo_output.stdout }}"
#    ## 検証環境できたら動作検証する
#    - name: 新規作成されたアプリ用ホスト情報をInventoryファイルに追加
#      add_host:
#        name: created-host
#        groups: created, app
#        ansible_host: "{{ created_host_ip }}"
#        ansible_port: 22
    - name: OSファミリーごとにグループ分け
      group_by:
        key: "{{ ansible_os_family }}"


  handlers:
    - name: sshd再起動
      service:
        name: sshd
        state: restarted
    