---
service_account_email: ""
credentials_file: ""
machine_type: "n1-standard-1"
image: "debian-8"
project_id: ""
zone: "europe-west1-b"
instance_names: ""

# Persistent disks settings
use_pd: "False"
disk_size: 100
disk_type: "pd-ssd"
