---
language: python
python: "2.7"

before_install:
  # Decrypt service account key file
  - openssl aes-256-cbc -K $encrypted_821a8b8e6c80_key -iv $encrypted_821a8b8e6c80_iv
    -in tests/gce-init-test-423986993e6b.json.enc -out tests/gce-init-test-423986993e6b.json
    -d

  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible and libcloud
  - pip install ansible
  - pip install apache-libcloud

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Check the role/playbook's syntax.
  - ansible-playbook tests/test.yml --syntax-check

  # Run the with ansible-playbook
  - ansible-playbook --extra-vars "service_account_email=travis-ci@gce-init-test.iam.gserviceaccount.com credentials_file=/home/travis/build/kal3v/gce-init/tests/gce-init-test-423986993e6b.json project_id=gce-init-test instance_names=bunny,rex" tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
